---
GnT Stock:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
GnT scDNA:
  :asset_type: plate
  :cherrypickable_target: false
  :input_plate: false
GnT Pico-XP:
  :asset_type: plate
GnT Pico End Prep:
  :asset_type: plate
GnT Pico Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
GnT MDA Norm:
  :presenter_class: Presenters::UntaggedPlatePassingPresenter
  :asset_type: plate
GnT Pico Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
GnT Pico Lib Pool XP:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class:
    name: Presenters::SimpleTubePresenter
    args:
      downstream_mx_tube:
        child_tube_purposes_to_limit:
          - 'LB Lib Pool Norm'
  :default_printer_type: :tube
