---
LBR Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
LBR mRNA Cap:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
LBR Globin:
  :asset_type: plate
LBR Ribo DNase:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
LBR Globin DNase:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
LBR RiboGlobin DNase:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
LBR Frag cDNA:
  :asset_type: plate
LBR Frag:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
LB cDNA:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
LB cDNA XP:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
