---
LB Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
LB Shear:
  :asset_type: plate
LB Post Shear:
  :asset_type: plate
LB End Prep:
  :asset_type: plate
LB Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  warnings:
    pcr_cycles_not_in:
      - 6
  :tag_layout_templates:
    - Illumina pipeline tagging
    - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
    - hWGS and RNAseq UDI tag layout v3
    - pWGS UDI tag layout v2 A
    - pWGS UDI tag layout v2 B
    - pWGS UDI tag layout v2 C
    - pWGS UDI tag layout v2 D
    - TS_pWGSA_UDI96
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSC_UDI_tag60_61_swap
    - TS_pWGSD_UDI96
    - TSRNAhWGS_UDI96
    - TS_pWGSA_UDI96v2
    - TSISC_UDI96
LB Lib PCR-XP:
  :asset_type: plate
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :file_links:
    - name: Download Concentration (nM) CSV
      id: concentrations_nm
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
  # :mark_under_represented_wells: true
LB Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class:
    name: Presenters::SimpleTubePresenter
    args:
      downstream_mx_tube:
        child_tube_purposes_to_limit:
          - 'LB Lib Pool Norm'
  :default_printer_type: :tube
